In [1]:
import numpy as np

In [13]:
x = [1, 2, 3, 4, 5, 6, 7, 8]
x = x[::-2]
x.reverse()
print(x)

[2, 4, 6, 8]


In [18]:
x2 = np.random.randint(0, 20, (3, 2))

In [19]:
x2

array([[ 5,  8],
       [11, 17],
       [13, 16]])

In [25]:
# Grab the first column of all the rows
x2[:, 0]

array([ 5, 11, 13])

In [30]:
# Grab the first row
# Empty slicing for rows can be omitted as it is added by default
x2[0, :]
x2[0, :1]

array([5])

In [34]:
x2_sub = x2[0]
x2_sub

array([5, 8])

In [36]:
x2_sub.shape

(2,)

In [37]:
x2_sub[1] = 99
x2_sub
x2

array([[ 5, 99],
       [11, 17],
       [13, 16]])

In [40]:
# reshaping arrays
grid = np.arange(1, 10)
print(grid)
grid = grid.reshape((3, 3))
grid
# Make sure that there are enough elements in the original array and it matches the dimesion you give while reshaping.

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
z = np.array([[1, 2], [3, 4]])
print(z.shape)
print(z)
z = z[:, np.newaxis]
print(z.shape)
print(z)


(2, 2)
[[1 2]
 [3 4]]
(2, 1, 2)
[[[1 2]]

 [[3 4]]]


In [55]:
# concatenation of arrays
# np.concat

grid = np.array([[1,2, 3], [4, 5, 6]])
new_grid = np.concatenate([grid, grid], axis=0)
new_grid

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [58]:
data= np.array([[1, 2], [3, 4], [5, 6]])
print(data.max(axis=1))

[2 4 6]


In [60]:
b = np.arange(10)
print(b)
np.where( b < 5, b, 10*b)

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])